---
- hosts: all
  gather_facts: no
  tasks:
  - name: ensure my ssh key
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '/home/dano0b/.ssh/id_rsa.pub') }}"
  - name: set timezone
    timezone:
      name: Europe/Berlin
